---
title: "Analysis of Ordovician and Silurian fossil occurrences as a function of geological context"
author: Peter Smits
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    fig_width: 7
    fig_height: 6
---


Step 0 is loading some useful packages for loading and cleaning data.

```{r packages, message = FALSE, results = 'hide'}

library(pacman)

p_load(here, janitor, tibble, readr, magrittr, dplyr, 
       tidyr, purrr, glue, stringr, 
       ggplot2, scales, grid, ggridges, viridis, ggrepel,
       compositions, geosphere,
       arm, rstan, rstanarm, brms,
       devtools)

library(notfossil)
# devtools::load_all()

```

There are several useful constants that will appear throughout the next few sections.
```{r constants}

theme_set(theme_bw(base_size = 20))

# colour blind palette of choice
blind <- c("#999999", "#E69F00", "#56B4E9", "#009E73", 
           "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# useful constants
shelly <- c('Brachiopoda', 'Anthozoa', 'Trilobita', 
            'Bivalvia', 'Gastropoda')#, 'Cephalopoda')
temp_range <- c(485.4, 419.2)          # ordovicain + silurian
hirnantian <- c(445.2, 443.8)

```

```{r child = '00_download_scrap.Rmd'}
```

```{r child = '01_prepare_data.Rmd'}
```

```{r child = '02_data_plots.Rmd'}
```


```{r system_info}

#devtools::session_info()

```
